language: cpp
git:
  quiet: true
  submodules: true
  depth: 3
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          packages:
            - autoconf
            - libtool
            - flex
            - bison
            - libeigen3-dev
            - libboost-all-dev
            - curl
            - libopencv-dev
            - libpcl-dev


before_install:
  - sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  - apt-get install -y ros-melodic-ros-base

  - eval "${MATRIX_EVAL}" 
  - bash ./scripts/install_dependencies_ci.sh

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage .. 
     - make -j$(nproc)

notifications:
  email: false